/** @format */

import axios from 'axios';
import Head from 'next/head';
import Image from 'next/image';

export default function Home(pokemon: React.ReactNode) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {console.log(pokemon)}
    </>
  );
}

export const getServerSideProps = async (contex: any) => {
  const res = await axios.get(`https://pokeapi.co/api/v2/pokemon/ditto`);

  return {
    props: {
      pokemon: res?.data,
    },
  };
};
