/** @format */

import axios from 'axios';
import { useRouter } from 'next/router';
import Head from 'next/head';
import Image from 'next/image';
import { useEffect } from 'react';

export default function Home(pokemon: React.ReactNode) {
  const router = useRouter();

  let token: string = '';

  if (typeof window !== 'undefined') {
    // You now have access to `window`
    if (window.sessionStorage) {
      const local = sessionStorage.getItem('token');
      if (typeof local === 'string') {
        token = local;
      }
    }
  }

  useEffect(() => {
    if (token.length > 0) {
      console.log('logeado', token);
    } else {
      router.push('/login');
    }
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {console.log(pokemon)}
      <h1>Holamundo</h1>
    </>
  );
}

export const getServerSideProps = async (contex: any) => {
  const res = await axios.get(`https://pokeapi.co/api/v2/pokemon/ditto`);

  return {
    props: {
      pokemon: res?.data,
    },
  };
};
