/** @format */

import axios from 'axios';
import { useRouter } from 'next/router';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import { Header } from '../components/Header/Header';
import { Task } from '../components/Task/Task';

export default function Home(pokemon: React.ReactNode) {
  const router = useRouter();

  let token: string = '';
  let email: string = '';
  const [tareas, setTareas] = useState('');

  if (typeof window !== 'undefined') {
    // You now have access to `window`
    if (window.sessionStorage) {
      const tokenlocal = sessionStorage.getItem('token');
      const emaillocal = sessionStorage.getItem('email');
      if (typeof tokenlocal === 'string') {
        token = tokenlocal;
      }
      if (typeof emaillocal === 'string') {
        email = emaillocal;
      }
    }
  }
  const task = async () => {
    if (email.length > 0 && token.length > 0) {
      const res: any = await axios.get(
        `https://back-next-app.vercel.app/api/task/all?${email}`,
        {
          headers: { 'x-access-token': `${token}` },
        }
      );
      setTareas(res);
    }
  };

  useEffect(() => {
    if (token.length > 0) {
      console.log('logeado', token);
    } else {
      router.push('/login');
    }

    task();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {console.log(pokemon)}
      {console.log(task)}
      <>
        <Header />
        <Task task={task} />
      </>
    </>
  );
}

export const getServerSideProps = async (contex: any) => {
  const res = await axios.get(`https://pokeapi.co/api/v2/pokemon/ditto`);

  return {
    props: {
      pokemon: res?.data,
    },
  };
};
